/**
 * Export utilities for SynBio constructs: FASTA, GenBank, JSON.
 */

import type { RestrictionSite, ORF } from "./synbio-dna-tools";

interface ExportData {
  name: string;
  sequence: string;
  sequenceType: string;
  assemblyType: string;
  hostOrganism: string;
  gcContent: number;
  cai: number;
  orfs: ORF[];
  restrictionSites: RestrictionSite[];
}

function wrap(text: string, width: number): string {
  const lines: string[] = [];
  for (let i = 0; i < text.length; i += width) {
    lines.push(text.substring(i, i + width));
  }
  return lines.join("\n");
}

export function exportFASTA(data: ExportData): string {
  const header = `>${data.name} | ${data.sequence.length} bp | ${data.sequenceType} | ${data.assemblyType} | ${data.hostOrganism} | GC:${data.gcContent.toFixed(1)}% | CAI:${data.cai.toFixed(3)}`;
  return header + "\n" + wrap(data.sequence, 60);
}

export function exportGenBank(data: ExportData): string {
  const bp = data.sequence.length;
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" }).toUpperCase().replace(",", "");

  let gb = "";
  gb += `LOCUS       ${data.name.padEnd(16)} ${String(bp).padStart(7)} bp    DNA     circular SYN ${dateStr}\n`;
  gb += `DEFINITION  Synthetic construct ${data.name}, ${data.assemblyType} assembly.\n`;
  gb += `ACCESSION   .\n`;
  gb += `VERSION     .\n`;
  gb += `KEYWORDS    synthetic biology; ${data.assemblyType}; ${data.hostOrganism}.\n`;
  gb += `SOURCE      synthetic construct\n`;
  gb += `  ORGANISM  synthetic construct\n`;
  gb += `COMMENT     Assembly method: ${data.assemblyType}\n`;
  gb += `            Host organism: ${data.hostOrganism}\n`;
  gb += `            GC content: ${data.gcContent.toFixed(1)}%\n`;
  gb += `            CAI: ${data.cai.toFixed(3)}\n`;
  gb += `            Generated by ORDEX SynBio Designer\n`;
  gb += `FEATURES             Location/Qualifiers\n`;
  gb += `     source          1..${bp}\n`;
  gb += `                     /organism="synthetic construct"\n`;
  gb += `                     /mol_type="other DNA"\n`;

  // ORFs
  for (const orf of data.orfs) {
    if (orf.strand === "+") {
      gb += `     CDS             ${orf.start + 1}..${orf.end}\n`;
    } else {
      gb += `     CDS             complement(${orf.start + 1}..${orf.end})\n`;
    }
    gb += `                     /note="ORF ${orf.length} aa, frame ${orf.frame}"\n`;
    gb += `                     /codon_start=1\n`;
  }

  // Restriction sites
  for (const site of data.restrictionSites) {
    gb += `     misc_feature    ${site.position + 1}..${site.position + site.sequence.length}\n`;
    gb += `                     /label="${site.enzyme}"\n`;
    gb += `                     /note="${site.overhang} overhang: ${site.overhangSeq}"\n`;
  }

  // Origin (sequence)
  gb += `ORIGIN\n`;
  const upper = data.sequence.toUpperCase();
  for (let i = 0; i < upper.length; i += 60) {
    const lineNum = String(i + 1).padStart(9);
    const chunks: string[] = [];
    for (let j = 0; j < 60 && i + j < upper.length; j += 10) {
      chunks.push(upper.substring(i + j, Math.min(i + j + 10, upper.length)).toLowerCase());
    }
    gb += `${lineNum} ${chunks.join(" ")}\n`;
  }
  gb += `//\n`;

  return gb;
}

export function exportJSON(data: ExportData): string {
  return JSON.stringify({
    name: data.name,
    sequenceType: data.sequenceType,
    assemblyType: data.assemblyType,
    hostOrganism: data.hostOrganism,
    length: data.sequence.length,
    gcContent: data.gcContent,
    cai: data.cai,
    sequence: data.sequence,
    orfs: data.orfs.map(o => ({ frame: o.frame, start: o.start, end: o.end, length: o.length, strand: o.strand })),
    restrictionSites: data.restrictionSites.map(s => ({ enzyme: s.enzyme, position: s.position, overhang: s.overhang })),
  }, null, 2);
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
