import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download, Loader2, Dna, FlaskConical } from "lucide-react";

interface Experiment {
  id: string;
  name: string;
  organism: string;
  cas_variant: string;
  target_gene: string | null;
  status: string;
  created_at: string;
  description: string | null;
}

interface Guide {
  id: string;
  guide_sequence: string;
  pam_sequence: string;
  version: number;
  status: string;
  efficiency_score: number | null;
  specificity_score: number | null;
  off_target_results: any;
  risk_assessment: string | null;
  created_at: string;
}

interface Log {
  id: string;
  title: string;
  content: string | null;
  log_type: string;
  created_at: string;
}

interface Props {
  experiment: Experiment;
  guides: Guide[];
  logs: Log[];
}

export function CrisprLabReport({ experiment, guides, logs }: Props) {
  const [generating, setGenerating] = useState(false);

  const generateReport = () => {
    setGenerating(true);

    const bestGuide = guides.reduce<Guide | null>((best, g) => {
      if (!best) return g;
      return (g.efficiency_score ?? 0) > (best.efficiency_score ?? 0) ? g : best;
    }, null);

    let md = `# CRISPR Lab Report: ${experiment.name}\n\n`;
    md += `**Generated:** ${new Date().toLocaleString()}\n\n---\n\n`;

    md += `## Experiment Overview\n\n`;
    md += `| Parameter | Value |\n|---|---|\n`;
    md += `| Organism | ${experiment.organism} |\n`;
    md += `| Cas Variant | ${experiment.cas_variant} |\n`;
    md += `| Target Gene | ${experiment.target_gene || "N/A"} |\n`;
    md += `| Status | ${experiment.status} |\n`;
    md += `| Created | ${new Date(experiment.created_at).toLocaleDateString()} |\n`;
    if (experiment.description) md += `| Description | ${experiment.description} |\n`;
    md += `\n`;

    md += `## Summary\n\n`;
    md += `- **Total Guide Designs:** ${guides.length}\n`;
    md += `- **Audit Log Entries:** ${logs.length}\n`;
    if (bestGuide) {
      md += `- **Best Efficiency Score:** ${(bestGuide.efficiency_score ?? 0).toFixed(1)}%\n`;
      md += `- **Best Specificity Score:** ${(bestGuide.specificity_score ?? 0).toFixed(1)}%\n`;
    }
    md += `\n`;

    if (guides.length > 0) {
      md += `## Guide Designs\n\n`;
      md += `| Ver | Sequence | PAM | Efficiency | Specificity | Status | Risk |\n`;
      md += `|-----|----------|-----|-----------|------------|--------|------|\n`;
      const sorted = [...guides].sort((a, b) => a.version - b.version);
      sorted.forEach((g) => {
        const seq = g.guide_sequence.length > 25 ? g.guide_sequence.slice(0, 25) + "…" : g.guide_sequence;
        md += `| v${g.version} | \`${seq}\` | ${g.pam_sequence} | ${g.efficiency_score?.toFixed(1) ?? "-"}% | ${g.specificity_score?.toFixed(1) ?? "-"}% | ${g.status} | ${g.risk_assessment || "-"} |\n`;
      });
      md += `\n`;

      // Off-target summary for best guide
      if (bestGuide?.off_target_results) {
        const ots = Array.isArray(bestGuide.off_target_results) ? bestGuide.off_target_results : [];
        if (ots.length > 0) {
          md += `### Off-Target Analysis (Best Guide v${bestGuide.version})\n\n`;
          md += `| Location | Mismatches | Region | CFD Score |\n`;
          md += `|----------|-----------|--------|----------|\n`;
          ots.slice(0, 10).forEach((ot: any) => {
            md += `| ${ot.location || "-"} | ${ot.mismatches ?? "-"} | ${ot.region || "-"} | ${ot.cfd_score?.toFixed(3) ?? "-"} |\n`;
          });
          if (ots.length > 10) md += `\n*...and ${ots.length - 10} more off-target sites*\n`;
          md += `\n`;
        }
      }
    }

    if (logs.length > 0) {
      md += `## Audit Log\n\n`;
      md += `| Date | Type | Title | Notes |\n`;
      md += `|------|------|-------|-------|\n`;
      logs.forEach((l) => {
        md += `| ${new Date(l.created_at).toLocaleString()} | ${l.log_type} | ${l.title} | ${(l.content || "-").slice(0, 80)} |\n`;
      });
      md += `\n`;
    }

    md += `---\n\n*Report generated by ORDEX Systems CRISPR Lab*\n`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${experiment.name.replace(/\s+/g, "_")}_crispr_report.md`;
    a.click();
    URL.revokeObjectURL(url);
    setGenerating(false);
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" />
          Lab Report
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="grid grid-cols-3 gap-2 text-xs">
          <div className="bg-muted rounded p-2 text-center">
            <Dna className="w-3.5 h-3.5 mx-auto mb-1 text-muted-foreground" />
            <div className="font-medium">{guides.length}</div>
            <div className="text-muted-foreground">Guides</div>
          </div>
          <div className="bg-muted rounded p-2 text-center">
            <FlaskConical className="w-3.5 h-3.5 mx-auto mb-1 text-muted-foreground" />
            <div className="font-medium">{logs.length}</div>
            <div className="text-muted-foreground">Log Entries</div>
          </div>
          <div className="bg-muted rounded p-2 text-center">
            <FileText className="w-3.5 h-3.5 mx-auto mb-1 text-muted-foreground" />
            <div className="font-medium capitalize">{experiment.status}</div>
            <div className="text-muted-foreground">Status</div>
          </div>
        </div>

        <Button onClick={generateReport} disabled={generating} className="w-full gap-2" size="sm">
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          Download CRISPR Report
        </Button>
        <p className="text-[10px] text-muted-foreground text-center">
          Includes experiment info, guide designs, off-targets, and audit log
        </p>
      </CardContent>
    </Card>
  );
}
