import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Loader2, Calendar, Beaker } from "lucide-react";

interface Culture {
  id: string;
  name: string;
  cell_line: string;
  passage_number: number;
  medium: string;
  temperature: number;
  co2_percent: number;
  humidity: number;
  status: string;
  notes: string | null;
  created_at: string;
}

interface Log {
  id: string;
  logged_at: string;
  confluence_percent: number | null;
  viability_percent: number | null;
  cell_count: number | null;
  ph: number | null;
  glucose_level: number | null;
  lactate_level: number | null;
  morphology_notes: string | null;
}

interface Analysis {
  id: string;
  analysis_type: string;
  result: any;
  created_at: string;
  credits_cost: number;
}

interface Props {
  culture: Culture;
  logs: Log[];
  analyses: Analysis[];
}

export function CultureLabReport({ culture, logs, analyses }: Props) {
  const [generating, setGenerating] = useState(false);

  const generateReport = () => {
    setGenerating(true);

    const sortedLogs = [...logs].sort(
      (a, b) => new Date(a.logged_at).getTime() - new Date(b.logged_at).getTime(),
    );

    const latestLog = sortedLogs[sortedLogs.length - 1];
    const oldestLog = sortedLogs[0];
    const duration = oldestLog && latestLog
      ? Math.round((new Date(latestLog.logged_at).getTime() - new Date(oldestLog.logged_at).getTime()) / 86400000)
      : 0;

    const avgConfluence = sortedLogs
      .filter((l) => l.confluence_percent != null)
      .reduce((s, l, _, a) => s + (l.confluence_percent ?? 0) / a.length, 0);
    const avgViability = sortedLogs
      .filter((l) => l.viability_percent != null)
      .reduce((s, l, _, a) => s + (l.viability_percent ?? 0) / a.length, 0);

    // Build markdown report
    let md = `# Lab Report: ${culture.name}\n\n`;
    md += `**Generated:** ${new Date().toLocaleString()}\n\n`;
    md += `---\n\n`;

    md += `## Culture Information\n\n`;
    md += `| Parameter | Value |\n|---|---|\n`;
    md += `| Cell Line | ${culture.cell_line} |\n`;
    md += `| Passage | P${culture.passage_number} |\n`;
    md += `| Medium | ${culture.medium} |\n`;
    md += `| Temperature | ${culture.temperature}°C |\n`;
    md += `| CO₂ | ${culture.co2_percent}% |\n`;
    md += `| Humidity | ${culture.humidity}% |\n`;
    md += `| Status | ${culture.status} |\n`;
    md += `| Created | ${new Date(culture.created_at).toLocaleDateString()} |\n`;
    md += `| Tracking Duration | ${duration} days |\n`;
    if (culture.notes) md += `| Notes | ${culture.notes} |\n`;
    md += `\n`;

    md += `## Summary Statistics\n\n`;
    md += `- **Total Observations:** ${logs.length}\n`;
    md += `- **Avg Confluence:** ${avgConfluence.toFixed(1)}%\n`;
    md += `- **Avg Viability:** ${avgViability.toFixed(1)}%\n`;
    if (latestLog) {
      md += `- **Latest Confluence:** ${latestLog.confluence_percent ?? "N/A"}%\n`;
      md += `- **Latest Viability:** ${latestLog.viability_percent ?? "N/A"}%\n`;
      md += `- **Latest pH:** ${latestLog.ph ?? "N/A"}\n`;
    }
    md += `\n`;

    if (sortedLogs.length > 0) {
      md += `## Observation Log\n\n`;
      md += `| Date | Confluence | Viability | Cell Count | pH | Notes |\n`;
      md += `|------|-----------|-----------|-----------|---|---------|\n`;
      sortedLogs.forEach((l) => {
        md += `| ${new Date(l.logged_at).toLocaleString()} | ${l.confluence_percent ?? "-"}% | ${l.viability_percent ?? "-"}% | ${l.cell_count?.toLocaleString() ?? "-"} | ${l.ph ?? "-"} | ${l.morphology_notes || "-"} |\n`;
      });
      md += `\n`;
    }

    if (analyses.length > 0) {
      md += `## AI Analysis History\n\n`;
      analyses.forEach((a) => {
        md += `### ${a.analysis_type.replace(/_/g, " ")} (${new Date(a.created_at).toLocaleDateString()})\n\n`;
        if (a.result?.summary) md += `${a.result.summary}\n\n`;
        if (a.result?.risk_score != null) md += `**Risk Score:** ${a.result.risk_score}/100 (${a.result.risk_level})\n\n`;
        if (a.result?.growth_phase) md += `**Growth Phase:** ${a.result.growth_phase}\n\n`;
      });
    }

    md += `---\n\n*Report generated by ORDEX Systems CellCulture AI*\n`;

    // Download as .md file
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${culture.name.replace(/\s+/g, "_")}_lab_report.md`;
    a.click();
    URL.revokeObjectURL(url);
    setGenerating(false);
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" />
          Lab Report
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="grid grid-cols-3 gap-2 text-xs">
          <div className="bg-muted rounded p-2 text-center">
            <Calendar className="w-3.5 h-3.5 mx-auto mb-1 text-muted-foreground" />
            <div className="font-medium">{logs.length}</div>
            <div className="text-muted-foreground">Observations</div>
          </div>
          <div className="bg-muted rounded p-2 text-center">
            <Beaker className="w-3.5 h-3.5 mx-auto mb-1 text-muted-foreground" />
            <div className="font-medium">{analyses.length}</div>
            <div className="text-muted-foreground">AI Analyses</div>
          </div>
          <div className="bg-muted rounded p-2 text-center">
            <FileText className="w-3.5 h-3.5 mx-auto mb-1 text-muted-foreground" />
            <div className="font-medium">P{culture.passage_number}</div>
            <div className="text-muted-foreground">Passage</div>
          </div>
        </div>

        <Button
          onClick={generateReport}
          disabled={generating}
          className="w-full gap-2"
          size="sm"
        >
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          Download Lab Report
        </Button>
        <p className="text-[10px] text-muted-foreground text-center">
          Includes culture info, observations, growth data, and AI insights
        </p>
      </CardContent>
    </Card>
  );
}
